application:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::TemplateAction
    defaults:
      template: 'application.php'

addingApp:
    path: /application
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::TemplateAction
    defaults:
      template: '/application/index.html.twig'
